# Generated by Django 5.2.6 on 2025-09-07 20:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wagtail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='body',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image_with_text', 8), ('image', 4), ('embed', 9)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')]}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('level', 0), ('text', 1)]], {}), 3: ('Wagtail.models.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right')]}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 4), ('text', 5), ('position', 6), ('caption', 7)]], {}), 9: ('Wagtail.models.ExternalEmbedBlock', (), {})}),
        ),
    ]
